# Generated by Django 4.2.6 on 2023-12-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_post_desc_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImg',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
