# Generated by Django 4.2.6 on 2023-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_post_postimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImg',
            field=models.ImageField(default='demo-image-default', upload_to='profile_images'),
        ),
    ]
