# Generated by Django 4.2.6 on 2024-01-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_comment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
