# Generated by Django 4.2.6 on 2024-01-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
